### ISSUE TITLE
[BUG] All messages get shown on load and popout

### ISSUE THREAD

**Issue by Moerill** [Moerill/fvtt-chat-notifications#13]
See title.

There seems to be some new behaviour in  FVTT0.8.x making messages always shown on startup, ignoring the max shown limit..?
Similar for popping out the chat.. This needs some further investigation.

No obvious console error. Also the background of the chat notifications "window" is not transparent anymore.  
This does not break anything, the module still works, just needs a (hopefully) small maintenance.

**Comment by friction1** [comment]
I have this issue as well. Running 0.8.6.

**Comment by DivertedCircle** [comment]
You can make the extra messages go away for a session by opening the settings window for the module. Still frustrating though.

**Comment by kimitsu** [comment]
Changing index.js@112 to
`const div = document.body.appendChild(html[0].querySelector('#chat-log').cloneNode(false));`
did the trick for me

**Comment by PalaNolho** [comment]
I also have this issue every time I select a token

**Comment by Meltyas** [comment]
m

> Changing index.js@112 to
> `const div = document.body.appendChild(html[0].querySelector('#chat-log').cloneNode(false));`
> did the trick for me

Made a PR with that code, lets hope @Moerill can add it.

Thanks for the fix.
