### ISSUE TITLE
[BUG] overlay breaks on /stream page

### ISSUE THREAD

**Issue by ardittristan** [Moerill/fvtt-chat-notifications#3]
**Describe the bug**
On the /stream page new messages create a duplicate popup on the top left of the screen

**To Reproduce**
1. Go to 'http://myfoundryurl.com/stream'
2. Send a new message
3. See double message

**Expected behavior**
The message should not appear in the top left.

**Screenshots/GIFs/Videos**
![image](https://user-images.githubusercontent.com/42787508/96451700-4620c580-1218-11eb-951c-f8dee584b1a4.png)

**Desktop:**
 - OS: Win10
 - Browser vivaldi (chromium)
 - FVTT Version 0.7.4
 - Module version 1.1.0

**Comment by Moerill** [comment]
So you'd want to have the module being completly disabled for stream view?

**Comment by ardittristan** [comment]
I think that would be the best option yeah, stream view can easily be detected with
`if (window.location.pathname === "/stream") {}`

**Comment by Moerill** [comment]
That check may have an issue with people having their fvtt instance in subdirectories (?) like my-cool-domain.com/fvtt
then that check would fail.
But the body does have the class "stream", so i'm going to check for that one.

**Comment by Moerill** [comment]
Update pushed, but only for fvtt 0.7.4 since i included the GSAP fix as well
