### ISSUE TITLE
[BUG] Error: User Player permission error

### ISSUE THREAD

**Issue by Mattrogers13** [Moerill/fvtt-chat-notifications#9]
**Describe the bug**
Error on the player side after clicking save and close in the module settings.

**Error Message**
Console information
```
Error: User Player Test lacks permission to update the World setting chat-notifications.4dP7AFD01OH1aqUz
foundry.js:3780:13
Uncaught (in promise) **Error: User Player Test lacks permission to update the World setting chat-notifications.4dP7AFD01OH1aqUz**
```

**To Reproduce**
1. Go to 'Configure Settings'
2. Go to the 'Module Settings' tab
3. Click on the 'Settings' button on the 'Hey, Listen - Chat Notifications' module.
4. Click "Save & Close"
5. Player sees displayed error on screen: Error: User Player Test lacks permission to update the World setting chat-notifications.4dP7AFD01OH1aqUz

**Expected behavior**
Expected no error to occur, however, it seems that the setting does take place and that the error message is the only issue.

**Module incompatibilities**
All modules have been turned off when reproducing this error. 

**Screenshots/GIFs/Videos**
![WjvtQmv](https://user-images.githubusercontent.com/48500042/101683211-a7a02c00-3a32-11eb-876a-9d2b943b0f3b.png)

**Desktop (please complete the following information):**
 - Mac 10.15.7 
 - tested in Firefox 83.0 and Chrome 87.0.4280.88
 - FVTT Version 0.7.8
 - Module version 1.2.1

**Additional context**
The module seems to still work besides throwing up an error. Not sure if it's a permissions thing on my end or not.

**Comment by Moerill** [comment]
Should be fixed no in 1.2.2
Though settings now are client side, so changing browser/pc will reset them
